### ISSUE TITLE
What the font?

### ISSUE THREAD

**Issue by atticus5** [minigdx/tiny#13]
What is the font used for the loading screen?

<img width="526" alt="Screenshot 2024-05-23 at 18 05 44" src="https://github.com/minigdx/tiny/assets/28069262/b92a0cd9-ecf6-45fe-b5c8-f51e626fe266">

**Comment by dwursteisen** [comment]
I « designed » it myself by trying to fit characters in a 8x8 square and by looking how other fonts succeeded to get an understanding character with few pixels. 

You can see all characters here: tiny-engine/src/commonMain/resources/_boot.png
